feeds:
  # Brede DK-nyheder (kan give støj – justér efter behov)
  - https://www.dr.dk/nyheder/service/feeds/allenyheder
  # Startup/tech-økosystem
  - https://techsavvy.media/feed/
  - https://bootstrapping.dk/feed/
  # Tilføj flere her…

keywords_gender:
  - kvinde
  - kvinder
  - kvind(e|elig|elige)
  - female
  - women
  - kvindeejet(e)?

keywords_startup:
  - iværksætter(i|e)?
  - startup(s)?
  - scaleup(s)?
  - stifter(e|en)?
  - founder(s)?
  - medstifter(e|en)?

export_limit: 200
