feeds:
  # ——— DK brede/erhverv/tech ———
  - https://www.dr.dk/nyheder/service/feeds/allenyheder
  - https://www.version2.dk/feeds/rss
  - https://www.computerworld.dk/rss/all
  - https://jyllands-posten.dk/rss
  - https://www.business.dk/rss
  - https://www.altinget.dk/rss/all
  - https://www.erhvervsplus.dk/rss

  # ——— DK startup/økosystem ———
  - https://bootstrapping.dk/feed/
  - https://techsavvy.media/feed/
  - https://nordicstartupnews.com/feed/
  - https://techbbq.dk/feed/
  - https://digitalhubdenmark.dk/feed/           # hvis 404, fjern den igen
  - https://startupcentral.dk/feed/              # fjern hvis 404

  # ——— Ligestilling/diversitet/kvinder ———
  - https://kvinfo.dk/feed/
  - https://kvinfo.dk/publikationer/feed/
  - https://kvindeokonomien.dk/feed/
  - https://www.female-leadership-academy.com/news/feed/
  - https://www.technordicadvocates.org/news/feed/
  - https://www.evenfounders.com/blogs/overview/feed/
  - https://nordicfemalefounders.dk/presse/pressemeddelelser/feed/

  # ——— Nordics/EU/international (kan have DK-cases) ———
  - https://www.eu-startups.com/feed/
  - https://siliconcanals.com/news/startups/feed/
  - https://techcrunch.com/feed/

  # ——— Google News metafeeds (meget effektive) ———
  - "https://news.google.com/rss/search?q=kvindelige%20iv%C3%A6rks%C3%A6ttere%20when:90d&hl=da&gl=DK&ceid=DK:da"
  - "https://news.google.com/rss/search?q=kvinder%20startup%20Danmark%20when:90d&hl=da&gl=DK&ceid=DK:da"
  - "https://news.google.com/rss/search?q=female%20founders%20Denmark%20when:90d&hl=en&gl=DK&ceid=DK:en"
  - "https://news.google.com/rss/search?q=kvindelig%20stifter%20virksomhed%20when:90d&hl=da&gl=DK&ceid=DK:da"
  - "https://news.google.com/rss/search?q=kvindeejet%20virksomhed%20when:90d&hl=da&gl=DK&ceid=DK:da"


keywords_gender:
  - kvinde
  - kvinder
  - kvindelig
  - kvindelige
  - female
  - women
  - woman
  - hun
  - kvindeejet
  - women-owned
  - women-led
  - female-led
  - rollemodel
  - girls in tech

keywords_startup:
  - iværksætter
  - iværksætteri
  - startup
  - scaleup
  - founder
  - co-founder
  - stifter
  - medstifter
  - accelerator
  - inkubator
  - pitch
  - venture
  - investering
  - funding
  - kapital
  - seed
  - pre-seed
  - serie a
  - angel
  - erhvervsleder

keywords_business:
  - erhverv
  - virksomhed
  - virksomheder
  - bestyrelse
  - direktør
  - ceo
  - leder
  - investering
  - investor
  - kapital
  - vækst
  - opkøb
  - eksport

exclude_keywords:
  - superliga
  - fodbold
  - håndbold
  - cykling
  - koncert
  - celebrity

weights:
  gender: 2
  startup: 2
  business: 1
  title_bonus: 1

min_score: 3
export_limit: 200

max_age_days: 120   # kun artikler nyere end 120 dage

