feeds:
  # Brede DK-nyheder (kan give støj – justér efter behov)
  - https://www.dr.dk/nyheder/service/feeds/allenyheder
  # Startup/tech-økosystem
  - https://techsavvy.media/feed/
  - https://bootstrapping.dk/feed/
  # Tilføj flere her…

keywords_gender:
  - kvinde
  - kvinder
  - female
  - women

keywords_startup:
  - iværksætter
  - startup
  - stifter
  - founder


export_limit: 200
