feeds:
  # ——— DK brede/erhverv/tech ———
  - https://www.dr.dk/nyheder/service/feeds/allenyheder
  - https://www.version2.dk/feeds/rss
  - https://www.computerworld.dk/rss/all
  - https://jyllands-posten.dk/rss
  - https://www.business.dk/rss
  - https://www.altinget.dk/rss/all
  - https://www.erhvervsplus.dk/rss

  # ——— DK startup/økosystem ———
  - https://bootstrapping.dk/feed/
  - https://techsavvy.media/feed/
  - https://nordicstartupnews.com/feed/
  - https://techbbq.dk/feed/
  - https://digitalhubdenmark.dk/feed/           # hvis 404, fjern den igen
  - https://startupcentral.dk/feed/              # fjern hvis 404

  # ——— Ligestilling/diversitet/kvinder ———
  - https://kvinfo.dk/feed/
  - https://kvinfo.dk/publikationer/feed/
  - https://kvindeokonomien.dk/feed/
  - https://www.female-leadership-academy.com/news/feed/
  - https://www.technordicadvocates.org/news/feed/
  - https://www.evenfounders.com/blogs/overview/feed/
  - https://nordicfemalefounders.dk/presse/pressemeddelelser/feed/
  - https://nordicfemalefounders.dk/feed/


  # ——— Nordics/EU/international (kan have DK-cases) ———
  - https://www.eu-startups.com/feed/
  - https://siliconcanals.com/news/startups/feed/
  - https://techcrunch.com/feed/

  # ——— Google News metafeeds (meget effektive) ———
  - "https://news.google.com/rss/search?q=kvindelige%20iv%C3%A6rks%C3%A6ttere%20when:90d&hl=da&gl=DK&ceid=DK:da"
  - "https://news.google.com/rss/search?q=kvinder%20startup%20Danmark%20when:90d&hl=da&gl=DK&ceid=DK:da"
  - "https://news.google.com/rss/search?q=female%20founders%20Denmark%20when:90d&hl=en&gl=DK&ceid=DK:en"
  - "https://news.google.com/rss/search?q=kvindelig%20stifter%20virksomhed%20when:90d&hl=da&gl=DK&ceid=DK:da"
  - "https://news.google.com/rss/search?q=kvindeejet%20virksomhed%20when:90d&hl=da&gl=DK&ceid=DK:da"
  - "https://news.google.com/rss/search?q=kvinder%20iv%C3%A6rks%C3%A6tteri%20when:90d&hl=da&gl=DK&ceid=DK:da"
  - "https://news.google.com/rss/search?q=kvindelig%20founder%20OR%20stifter%20when:90d&hl=da&gl=DK&ceid=DK:da"
  - "https://news.google.com/rss/search?q=women%20founders%20Denmark%20when:90d&hl=en&gl=DK&ceid=DK:en"
  - "https://news.google.com/rss/search?q=kvindeejet%20virksomhed%20when:90d&hl=da&gl=DK&ceid=DK:da"
  - "https://news.google.com/rss/search?q=kvinder%20iv%C3%A6rks%C3%A6tteri%20when:90d&hl=da&gl=DK&ceid=DK:da"
  - "https://news.google.com/rss/search?q=kvindelig%20founder%20when:90d&hl=da&gl=DK&ceid=DK:da"
  - "https://news.google.com/rss/search?q=site:evenfounders.com&hl=da&gl=DK&ceid=DK:da"
  - "https://news.google.com/rss/search?q=site:nordicfemalefounders.dk&hl=da&gl=DK&ceid=DK:da"
  - "https://news.google.com/rss/search?q=site:lastobject.com&hl=da&gl=DK&ceid=DK:da"
  - "https://news.google.com/rss/search?q=site:roccamore.com&hl=da&gl=DK&ceid=DK:da"
  - "https://news.google.com/rss/search?q=site:momkind.dk&hl=da&gl=DK&ceid=DK:da"
  - "https://news.google.com/rss/search?q=site:thefootprintfirm.com&hl=da&gl=DK&ceid=DK:da"
  - "https://news.google.com/rss/search?q=site:femaleinvest.com&hl=da&gl=DK&ceid=DK:da"
  - "https://news.google.com/rss/search?q=site:nordicfemalefounders.dk&hl=da&gl=DK&ceid=DK:da"
  - "https://news.google.com/rss/search?q=site:em.dk&hl=da&gl=DK&ceid=DK:da"





keywords_gender:
  - kvinde
  - kvinder
  - kvindelig
  - kvindelige
  - female
  - women
  - woman
  - hun
  - kvindeejet
  - women-owned
  - women-led
  - female-led
  - rollemodel
  - girls in tech

keywords_startup:
  - iværksætter
  - iværksætteri
  - startup
  - scaleup
  - founder
  - co-founder
  - stifter
  - medstifter
  - accelerator
  - inkubator
  - pitch
  - venture
  - investering
  - funding
  - kapital
  - seed
  - pre-seed
  - serie a
  - angel
  - erhvervsleder

keywords_business:
  - erhverv
  - virksomhed
  - virksomheder
  - bestyrelse
  - direktør
  - ceo
  - leder
  - investering
  - investor
  - kapital
  - vækst
  - opkøb
  - eksport

exclude_keywords:
  - superliga
  - football
  - soccer
  - fodbold
  - handball
  - håndbold
  - cycling
  - cykling
  - concert
  - koncert
  - celebrity
  - celebrities
  - gossip


weights:
  gender: 2
  startup: 2
  business: 1
  title_bonus: 1

min_score: 2
export_limit: 200

max_age_days: 1095   # kun artikler nyere end 120 dage

press_pages:
  - url: "https://nordicfemalefounders.dk/presse/pressemeddelelser"
    domain: "nordicfemalefounders.dk"
    max_items: 30
    href_include: "/presse/"


# === Curated mode (nyt) ===
curated_mode: true
max_age_days: 1095   # 3 år

exclude_keywords:
  - superliga
  - football
  - soccer
  - fodbold
  - handball
  - håndbold
  - cycling
  - cykling
  - concert
  - koncert
  - celebrity
  - celebrities
  - gossip
  - entertainment

feeds:
  - "https://kvinfo.dk/publikationer/feed/"
  - "https://news.google.com/rss/search?q=site:femaleinvest.com&hl=da&gl=DK&ceid=DK:da"
  - "https://news.google.com/rss/search?q=site:evenfounders.com&hl=da&gl=DK&ceid=DK:da"
  - "https://news.google.com/rss/search?q=site:thefootprintfirm.com&hl=da&gl=DK&ceid=DK:da"

press_pages:
  - url: "https://nordicfemalefounders.dk/presse/pressemeddelelser"
    domain: "nordicfemalefounders.dk"
    max_items: 50
    href_include: "/presse/"

press_pages:
  - url: "https://kvinfo.dk/publikationer/"
    domain: "kvinfo.dk"
    max_items: 80
    allow_pdf: true

press_pages:
  - url: "https://www.evenfounders.com/blogs/overview"
    domain: "evenfounders.com"
    max_items: 50
    href_include: "/blogs/"



