feeds:
  # DK brede / tech
  - https://www.dr.dk/nyheder/service/feeds/allenyheder
  - https://www.version2.dk/feeds/rss
  - https://www.computerworld.dk/rss/all

  # DK startup-økosystem
  - https://bootstrapping.dk/feed/
  - https://techsavvy.media/feed/
  - https://nordicstartupnews.com/feed/

  # EU / internationalt (kan have danske historier)
  - https://www.eu-startups.com/feed/
  - https://siliconcanals.com/news/startups/feed/


keywords_gender:
  - kvinde
  - kvinder
  - kvindelig
  - female
  - women
  - woman
  - hun

keywords_startup:
  - iværksætter
  - startup
  - scaleup
  - founder
  - stifter
  - medstifter
  - entreprenør
  - erhverv
  - virksomhed
  - erhvervsleder

keywords_business:
  - erhverv
  - virksomhed
  - virksomheder
  - investering
  - investor
  - kapital
  - funding
  - venture
  - direktør
  - ceo
  - leder
  - bestyrelse

export_limit: 200
