feeds:
  # Nyheder
  - https://www.dr.dk/nyheder/service/feeds/allenyheder
  - https://www.berlingske.dk/rss
  - https://finans.dk/rss
  - https://borsen.dk/nyheder/rss
  # Startup/tech
  - https://bootstrapping.dk/feed/
  - https://techsavvy.media/feed/
  - https://techcrunch.com/feed/   # internationalt
  - https://nordicstartupnews.com/feed/ 

keywords_gender:
  - kvinde
  - kvinder
  - kvindelig
  - female
  - women
  - woman
  - hun

keywords_startup:
  - iværksætter
  - startup
  - scaleup
  - founder
  - stifter
  - medstifter
  - entreprenør
  - erhverv
  - virksomhed
  - erhvervsleder

export_limit: 200
