name: Update news.json and deploy

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # every hour

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r aggregator/requirements.txt

      - name: Run aggregator
        run: |
          python aggregator/aggregator.py

      - name: Commit updated news.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ -n $(git status --porcelain) ]]; then
            git add news.json
            git commit -m "chore: update news.json ($(date -u +'%Y-%m-%dT%H:%M:%SZ'))"
            git push
          else
            echo "No changes to commit"
          fi
